[package]
name = "maglab"
version = "0.1.0"
authors = ["mihaimaganu17"]
edition = "2018"


[dependencies]
crossterm = "0.19"
tui = { version = "0.15", default-features = false, features = ['crossterm'] }
